version: "3.7"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123!@#
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: 123!@#

